### ISSUE TITLE
 error

### ISSUE THREAD

**Issue by ivanoff13** [pq-yang/PGDiff#5]
tell me how to fix the error?
File "inference_pgdiff.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2
![Снимок экрана 2023-10-31 174234](https://github.com/pq-yang/PGDiff/assets/20181974/c144f6f6-111e-42b7-b821-07e0df720302)

**Comment by pq-yang** [comment]
Hi @ivanoff13, `pip install opencv-python` should fix this error. 

In addition, I would like to kindly remind you to go through the [Installation](https://github.com/pq-yang/PGDiff#diamonds-installation) section in the README file before you could run the inference scripts. Thanks.
